In [101]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [103]:
data = pd.read_csv('car.data')

In [105]:
data

buying maintenance  doors persons lug_boot safety  class
0     vhigh       vhigh      2       2    small    low  unacc
1     vhigh       vhigh      2       2    small    med  unacc
2     vhigh       vhigh      2       2    small   high  unacc
3     vhigh       vhigh      2       2      med    low  unacc
4     vhigh       vhigh      2       2      med    med  unacc
...     ...         ...    ...     ...      ...    ...    ...
1723    low         low  5more    more      med    med   good
1724    low         low  5more    more      med   high  vgood
1725    low         low  5more    more      big    low  unacc
1726    low         low  5more    more      big    med   good
1727    low         low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [107]:
# we will only consider buying, maintenance,safety 
X = data[['buying', 'maintenance','safety']].values
y = data[['class']]
print(X,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


In [109]:
# converting the string data to int
Le = LabelEncoder()
for i in range(len(X[0])):
    X[:, i] = Le.fit_transform(X[:, i])

print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [111]:
label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}

y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


C:\Users\Anay\AppData\Local\Temp\ipykernel_4356\2862010092.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


In [148]:
# create a model
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

In [150]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.2,random_state=69)

In [152]:
knn.fit(X_train,y_train)

C:\Users\Anay\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=25)

In [154]:
y_pred = knn.predict(X_test)

In [156]:
acc = metrics.accuracy_score(y_test,y_pred)

In [158]:
print("The predictions are: ",y_pred)
print("The accuracy score is ",acc)

The predictions are:  [0 0 0 ... 0 0 0]
The accuracy score is  0.7057122198120029
